---
- hosts: all
  become: yes
  tasks:
#  - name: Ensure NTP (for time sychronization) is installed.
#    yum: name=ntp state-present
#  - name: Ensure NTP is running.
#    service: name=ntpd state=started enabled=yes

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - mcrypt
      - nginx
      - php5-cli
      - php5-curl
      - php5-fpm
      - php5-intl
      - php5-json
      - php5-mcrypt
      - php5-sqlite
      - sqlite3
      - mysql-server
      - libapache2-mod-auth-mysql
      - php5-mysql
      - python-mysqldb
      - apache2
      
  - name: Remove test DB
    mysql_db:
      db: test
      state: absent

  - name: Create a new database with name 'this_is_a_dummy_database'
    mysql_db:
      name: this_is_a_dummy_data_database
      state: present

  - name: creating an user with admin priviledges
    mysql_user: 
      name: admin 
      password: admin
      priv: '*.*:ALL,GRANT'
      state: present


  - name: create /var/www/ directory
    file: dest=/var/www/ state=directory owner=www-data group=www-data mode=0700


  - name: Download Composer Installer
    get_url: 
      url: https://getcomposer.org/installer
      dest: /tmp/composer-install.php
      mode: 0755

  - name: Run Composers Installer
    command: > 
      php composer-install.php
      chdir=/tmp
      creates=/usr/local/bin/composer

  - name: Move Composer into globally-accessible location
    shell: > 
      mv /tmp/composer.phar /usr/local/bin/composer
      creates=/usr/local/bin/composer
